### ISSUE TITLE
Tracking Issue - Core Entities and Components

### ISSUE THREAD

**Issue by fkarg** [singularity-rs/singularity-rs#2]
## General, Core Game functionality
<br/><br/>

- [ ] Unit
    - [ ] Moving
        - [ ] Position
        - [ ] Velocity
        - [ ] Acceleration
    - [ ] UnitType (Produce, Carry, Build, Defend)
    - [ ] Graph-Based Pathfinding module
    - [ ] Communication: Getting Tasks (finishing, failing, impossible to do, ...)
    - [ ] Drawable
<br/><br/>
    - [ ] ResourceCarrying
    - [ ] ActiveTask

<br/><br/>

- [ ] Tasks
    - [ ] JobType
    - [ ] BeginPlatform
    - [ ] EndPlatform
    - [ ] DoWorkForPlatformAction
    - [ ] ResourceType

<br/><br/>

- [ ] FreeMovingUnit (not MVP)
    - [ ] Moving
        - [ ] Position
        - [ ] Velocity
        - [ ] Acceleration
    - [ ] A\*-based pathfinding
    - [ ] Flocking / FlockingGroups
        - [ ] FlockingGroupNumber
        - [ ] GroupMiddle
        - [ ] GroupAverage
    - [ ] TeamNumber (own or enemy/other faction)
    - [ ] ReportState
    - [ ] Selectable
    - [ ] Drawable
    - [ ] LoseHealth
<br/><br/>
    - [ ] Shooting
    - [ ] TargetingAt
    - [ ] UserControl
    - [ ] AIControl
<br/><br/>
    - [ ] Settler (not MVP)
    - [ ] Transporter (not MVP)
    - [ ] Communicator (not MVP)

<br/><br/>

- [ ] StoryManager
    - [ ] Level
        - [ ] Goals
        - [ ] Enemies
    - [ ] Map
        - [ ] Fog Of War
        - [ ] CollisionMap
            - [ ] Collidable objects on Map
        - [ ] ResourceMap
        - [ ] StructureMap
        - [ ] UnitMap
        - [ ] Camera (? -> put that somewhere else !!)

<br/><br/>

- [ ] Graph
    - [ ] Nodes
    - [ ] Edges

<br/><br/>

- [ ] Platform
    - [ ] PlatformType
    - [ ] Position
    - [ ] ResourcesOnPlatform
    - [ ] IsBluePrint
    - [ ] Selectable
    - [ ] ReportState
    - [ ] PauseActions
    - [ ] LoseHealth
    - [ ] Drawable
    - [ ] ConnectedPlatforms
    - [ ] RoutingTable
<br/><br/>
    - [ ] ProduceResource (Which)
    - [ ] RequestResources
    - [ ] RemoveResource
    - [ ] CreateResource
    - [ ] DefendWithBullets
    - [ ] DefendWithLaser
    - [ ] RequestUnits
