### ISSUE TITLE
Tracking Issue - Systems

### ISSUE THREAD

**Issue by fkarg** [singularity-rs/singularity-rs#5]
## Systems
<br/><br/>

- [ ] Setting Blueprints
    - Platforms
    - Road (?)
    - Graph
    - DistributionManager -> notification: ready to build
    - Map
    - BuildMenu
- [ ] Building Blueprints
    - Setting Blueprints
    - Units
    - Tasks
    - Resources
    - Paths / Roads
    - DistributionManager -> creating tasks for units to put resources there
- [ ] Selecting Platforms
    - Platforms
    - Map/StructureMap
    - Camera
    - SelectionStats
    - Catching Input for specific Platform correctly
- [ ] Update resource numbers on Platforms
    - Part 1:
        - Resources
        - Time
        - CreateResource
    - Part 2:
        - Resource
        - Units
        - Tasks
    - Actually necessary?
- [ ] Making Sliders work for how many units should do what on which Graph
    - GraphUnitStats
    - DistributionManager
    - Probably only a channel, not a System
- [ ] Updating all the UI elements
    - All the UI elements
    - ...
    - some other way in amethyst?
- [ ] Moving & adjusting Camera
    - Input-catching stuff
    - GameScreen
    - Camera
- [ ] Pause / Unpause Game
    - Input-catching stuff
    - PauseScreen
    - Buttons
- [ ] Update on achieved goals/trigger next goals/trigger Enemies coming/ ....
    - Extensive logging all over the place
    - guess this needs to be split up more ...
<br/><br/>
- [ ] Moving (Free-) Units and Resources
    - Map(s)
    - Units
    - FreeMovingUnits
    - Resources
    - Time-based Update-cycles
- [ ] Do Path-finding for these needed
    - Map(s)
    - PathFinding Algorithms implemented
    - Units
    - FreeMovingUnits
<br/><br/>
- [ ] Produce & Consume Resources
    - Resources
    - (producing) Platforms
    - ResourceMap
- [ ] Transport Resources
    - Units
    - DistributionManager
    - Graph
    - GraphPathPlanning
    - Resources
    - Platforms
    - Roads
    - Tasks
    - System: Movement
- [ ] Provide new Tasks for Units asking for them -> DistributionManager
    - [ ] JoinGraphs
    - [ ] SplitGraphs
    - [ ] AddToGraph
    - [ ] Calculate flowgraphs of resources (async? MVP?)
    - Units
    - Tasks
    - Resources
    - Platforms
    - Roads
    - Graph
    - GraphPathPlanning
    - Channels for communication
<br/><br/>
- [ ] 'StoryManager' for advancing the story / levels upon reaching goals
    - Map(s)
    - Level(s)
    - Goals
    - Loading level descriptions
    - ReportState(s)
- [ ] Planning Military maneuvers from AI (-> MilitaryManager; not MVP)
    - FreeMovingUnit
    - TeamNumber
    - Map(s)
- [ ] Planning Building and Resource aquiring from AI
    - DistributionManager
    - MilitaryManager
